version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teddyopenfinance-app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend
    command: ["npm", "run", "start:prod"]

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
